### ISSUE TITLE
Build failing with build pack

### ISSUE THREAD

**Issue by Charizard** [anycable/heroku-anycable-go#2]
Build failed in Heroku with message `flag provided but not defined: -v`

Debugged it to [this line](https://github.com/anycable/heroku-anycable-go/blob/bb43f595f445a9636f08e3a9d1e77a0c1687f199/bin/compile#L38). This needs to change to `--version` as `-v` is not a valid flag.

Let me know if you would like me to open a PR. And thanks for the awesome work.

**Comment by palkan** [comment]
Oops, sorry( The older version doesn't have `-v` flag. I've replaced it with `-h`; should work now, check, please

**Comment by Charizard** [comment]
@palkan Hey, I still see the build failing.

**Comment by palkan** [comment]
I see. Fixing

**Comment by palkan** [comment]
Check again, please

**Comment by Charizard** [comment]
@palkan Thanks for the quick response. This works now.
